Creating a SQLite3 database of earthquake travel-time data
Files begin in input format for struct3dp inversion program

First read in the travel time data from the different files

In [54]:
import pandas as pd
import numpy as np

# define the directory that has the struct3dp data files
modelname='Run_230'
rundir='/Users/ulberg/research/MSH/crosson/Runs'
datadir='{}/{}/Data'.format(rundir,modelname)

# These file names are always associated with an inversion
stafile='combined.sta' # the stations that recorded travel times
eqobsfile='quakes.obs' # the travel time observations for earthquakes
eqlocfile='quakes.loc' # the locations of earthquakes
exobsfile='explos.obs' # the travel time observations for explosions
exlocfile='explos.loc' # the locations of explosions

sta=pd.read_csv(datadir + '/' + stafile, names=['Station','Longitude','Latitude','Depth'], sep=' ', skipinitialspace=True)
obs_eq=pd.read_csv(datadir + '/' + eqobsfile, names=['SourceID','Station','Phase','ArrivalTime','Uncertainty'], sep=' ', skipinitialspace=True)
loc_eq=pd.read_csv(datadir + '/' + eqlocfile, names=['SourceID','Longitude','Latitude','Depth','EventTime'], sep=' ', skipinitialspace=True)
obs_ex=pd.read_csv(datadir + '/' + exobsfile, names=['SourceID','Station','Phase','ArrivalTime','Uncertainty'], sep=' ', skipinitialspace=True)
loc_ex=pd.read_csv(datadir + '/' + exlocfile, names=['SourceID','Longitude','Latitude','Depth','EventTime'], sep=' ', skipinitialspace=True)

We need to relate the source id's to the antelope database so we can get a full origin time for the event. Start with the ones that were recorded on the iMUSH broadband instruments (SourceID starts with '4', '5', '6')

In [147]:
# sources were organized based on the first 1 or 2 digits of the id
# define what the initial character means
src_antelope=['4','5','6']
dict_ant={}
for k in src_antelope:
    for j in range(1,5):
        dict_ant[k+str(j)]='201' + k + '_Q' + str(j)
        
src_pnsn=['9']
src_shot=['8'] # or anything else

# read in the first and second characters in the SourceID, this bit could use some cleaning
srcID0=loc_eq['SourceID'].apply(lambda x: x[0])
# srcID1=loc_eq['SourceID'].apply(lambda x: x[1])
# srcID01=loc_eq['SourceID'].apply(lambda x: x[:2])
# print('Data types: ' + str(srcID0.unique()))

# is it from antelope?
# isAnt=srcID0.apply(lambda x: x in src_antelope)
loc_eq['dbname']=loc_eq['SourceID'].apply(lambda x: x[:2]).map(dict_ant)
# loc_eq.dbname.value_counts() # how many events from each quarter are there?

# if the source is in antelope, get the antelope orid
loc_eq['SourceID'][loc_eq['dbname'].notnull()]
loc_eq['orid']=loc_eq[['SourceID','dbname']].apply(lambda x: x[0][-5:-1] if pd.notnull(x[1]) else 'NaN', axis=1)

In [149]:
loc_eq

        SourceID  Longitude  Latitude   Depth  EventTime   dbname  orid
0       4301394p -122.47190  45.85370   0.000     26.897  2014_Q3  1394
1       4301395p -122.65570  45.56330  15.500     41.314  2014_Q3  1395
2       4301396p -122.42670  46.17240   0.123     28.559  2014_Q3  1396
3       4301401p -122.45580  46.35260   1.420     30.893  2014_Q3  1401
4       4301404p -121.91530  46.83280  10.400     52.527  2014_Q3  1404
5       4301408p -122.41540  45.64970   0.068     31.886  2014_Q3  1408
6       4301414p -121.96370  46.94320  12.400     55.671  2014_Q3  1414
7       4301415p -122.80370  45.65530  17.800     14.818  2014_Q3  1415
8       4301444p -121.56930  46.36120   0.100     14.227  2014_Q3  1444
9       4301446p -121.78880  46.41850   6.300     56.861  2014_Q3  1446
10      4301473p -121.48820  46.89630  -1.100     40.670  2014_Q3  1473
11      4301479p -122.66520  46.81980  16.000     52.229  2014_Q3  1479
12      4301489p -121.62330  46.53620  -1.400     59.185  2014_Q3  1489
13      4301507p -121.89120  46.88240  20.139     13.805  2014_Q3  1507
14      4301508p -122.49750  45.33450  27.700     22.585  2014_Q3  1508
15      4301529p -122.38270  45.64210   5.327     18.112  2014_Q3  1529
16      4301545p -122.39880  46.37760   1.347     16.442  2014_Q3  1545
17      4301546p -122.38850  45.63870   5.325     31.339  2014_Q3  1546
18      4301551p -121.93320  45.81530   7.800      1.888  2014_Q3  1551
19      4301552p -121.92900  45.81530   8.200     35.230  2014_Q3  1552
20      4301554p -122.41520  46.45430  13.200     22.235  2014_Q3  1554
21      4301555p -121.91250  46.83550  10.400     18.813  2014_Q3  1555
22      4301557p -121.61730  46.53700  -1.200     39.814  2014_Q3  1557
23      4301558p -121.96300  46.93970  12.000     29.326  2014_Q3  1558
24      4301560p -122.80030  45.65150  19.000     39.624  2014_Q3  1560
25      4301563p -122.67440  46.86020  20.818     11.394  2014_Q3  1563
26      4301564p -122.10940  47.79830   2.809     33.084  2014_Q3  1564
27      4301565p -121.77300  46.55830   8.100     57.628  2014_Q3  1565
28      4301567p -122.29450  46.66100  18.100     59.586  2014_Q3  1567
29      4301568p -121.93020  45.83480   8.700     30.876  2014_Q3  1568
..           ...        ...       ...     ...        ...      ...   ...
869  9061140717p -121.69817  45.32167   3.710      0.010      NaN   NaN
870  9061140782p -121.70167  45.31917   3.460     40.270      NaN   NaN
871  9061143812p -121.73250  46.61867   8.440     51.280      NaN   NaN
872  9061144147p -122.94800  45.93617  25.130     33.740      NaN   NaN
873  9061144942p -122.64167  46.57350  22.230     29.270      NaN   NaN
874  9061146437p -121.70100  45.28317   7.500     55.990      NaN   NaN
875  9061164776p -122.19900  47.17450  15.850     28.970      NaN   NaN
876  9061166001p -122.20550  47.17267  16.620     47.050      NaN   NaN
877  9061167541p -122.41067  46.49467  18.360     59.260      NaN   NaN
878  9061162617p -122.20150  47.17267  16.570     12.800      NaN   NaN
879  9061163187p -122.41550  46.48517  18.160     36.190      NaN   NaN
880  9061166217p -121.95767  46.77650   7.520     30.940      NaN   NaN
881  9061167147p -122.81317  45.47467  26.650     43.880      NaN   NaN
882  9061171897p -121.89617  46.84633   8.710     52.280      NaN   NaN
883  9061173197p -121.88867  47.17567  15.160     26.970      NaN   NaN
884  9061180422p -122.61917  45.81617  15.630     32.700      NaN   NaN
885  9061203191p -123.11067  46.18467  22.140     21.130      NaN   NaN
886  9061204121p -122.43817  46.13617  16.230      0.010      NaN   NaN
887  9061207296p -123.10767  46.16117  22.570     43.760      NaN   NaN
888  9061211886p -122.14717  46.62617  14.480     48.500      NaN   NaN
889  9061200622p -122.05517  46.27267   8.810     27.140      NaN   NaN
890  9061202782p -121.93367  46.81717   9.520     10.470      NaN   NaN
891  9061218232p -122.39450  47.24650  24.810     43.700      NaN   NaN
892  9061221742p -121.75500  46.85217   0.730      0.310      NaN   NaN
893  9061221922p -121.94067  46.86100   9.630     14.200      NaN   NaN
894  9060824482p -122.18700  46.19750   0.010     28.790      NaN   NaN
895  9060828637p -122.18720  46.20820   5.110     21.850      NaN   NaN
896  9060828732p -122.17780  46.20500   6.020     29.110      NaN   NaN
897  9060828737p -122.17670  46.20400   5.160     25.330      NaN   NaN
898  9060829072p -122.17420  46.20030   4.850     56.980      NaN   NaN

[899 rows x 7 columns]